version: "3.6"

services:
  web-ui:
    image: httpd
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./dist
        target: /usr/local/apache2/htdocs/
    ports:
      - 8090:80
